### ISSUE TITLE
Unpin non-existent files

### ISSUE THREAD

**Issue by MasterAwesome** [MasterAwesome/android_device_xiaomi_laurel_sprout#1]
```
11-10 23:19:33.957  1321  1718 E PinnerService: Could not pin file /apex/com.android.art/javalib/core-oj.jar
11-10 23:19:33.957  1321  1718 E PinnerService: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
11-10 23:19:33.957  1321  1718 E PinnerService:         at libcore.io.Linux.open(Native Method)
11-10 23:19:33.957  1321  1718 E PinnerService:         at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
11-10 23:19:33.957  1321  1718 E PinnerService:         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
11-10 23:19:33.957  1321  1718 E PinnerService:         at android.system.Os.open(Os.java:410)
11-10 23:19:33.957  1321  1718 E PinnerService:         at com.android.server.PinnerService.pinFileRanges(PinnerService.java:787)
11-10 23:19:33.957  1321  1718 E PinnerService:         at com.android.server.PinnerService.pinFile(PinnerService.java:667)
11-10 23:19:33.957  1321  1718 E PinnerService:         at com.android.server.PinnerService.handlePinOnStart(PinnerService.java:252)
11-10 23:19:33.957  1321  1718 E PinnerService:         at com.android.server.PinnerService.access$1400(PinnerService.java:87)
11-10 23:19:33.957  1321  1718 E PinnerService:         at com.android.server.PinnerService$PinnerHandler.handleMessage(PinnerService.java:995)
11-10 23:19:33.957  1321  1718 E PinnerService:         at android.os.Handler.dispatchMessage(Handler.java:107)
11-10 23:19:33.957  1321  1718 E PinnerService:         at android.os.Looper.loop(Looper.java:214)
11-10 23:19:33.957  1321  1718 E PinnerService:         at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by MasterAwesome** [comment]
Fixed in 9d93a5f06530f3597d9c7b672436ed4c452b88eb
